name: Deploy to ECS

on:
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build, tag, and push Docker image
        env:
          IMAGE_NAME: helloworld-nextjs
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $IMAGE_NAME:$IMAGE_TAG .
          docker tag $IMAGE_NAME:$IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_NAME:$IMAGE_TAG
          
  deploy:
    needs: build
    runs-on: aws-ec2
    steps:
      -  name: pull the image from the dockerhub
         run: docker pull this23/helloworld-nextjs:4a8d3896f47e7a282b5dcbaf5b71e9163e36dc0e
      -  name: Delete the old container
         run: docker rm -f app
      -  name: Run the docker container
         run : docker run -d -p 3000:3000 --name app this23/helloworld-nextjs:4a8d3896f47e7a282b5dcbaf5b71e9163e36dc0e
      
